#!/bin/sh

colo=$2
case "$1" in
  start)
    echo "Starting . . . . . ."
    setsid /usr/bin/sing-box -c /etc/sing-box/config.json > /dev/null 2>&1 &
  ;;
  stop)
    echo "Stopping . . . . . ."
    pkill sing-box
  ;;
  status)
    meta=`curl -x socks5://127.0.0.1:1080 -s https://speed.cloudflare.com/meta -m 5 | awk -F\" '{print $22}'`
    echo "$(date) $meta"
  ;;
  HK)
    echo "Starting . . . . . ."
    i=1
    while [ $i -le 9 ]; do
      setsid /usr/bin/sing-box -c /etc/sing-box/config.json > /dev/null 2>&1 &
      sleep 3
      meta=`curl -x socks5://127.0.0.1:1080 -s https://speed.cloudflare.com/meta -m 5 | awk -F\" '{print $22}'`
      echo "$(date) $meta"
      if [[ "$meta" != "HK" ]]; then
        pkill sing-box
        sleep 1
      else
        break
      fi
      let i++
    done
  ;;
  *)
    echo "Usage: /etc/init.d/sing-box {start|stop}"
    exit 1
  ;;
esac
exit 0
