#!/bin/sh

colo=$2
case "$1" in
  start)
    echo "Starting . . . . . ."
    if [[ -z "$colo" ]]; then
      setsid /usr/bin/sing-box -c /etc/sing-box/config.json > /dev/null 2>&1 &
    else
      i=1
      while [ $i -le 9 ]; do
        setsid /usr/bin/sing-box -c /etc/sing-box/config.json > /dev/null 2>&1 &
        sleep 3
        meta=`curl -x socks5://127.0.0.1:1080 -s https://speed.cloudflare.com/meta -m 5 | awk -F\" '{print $22}'`
        echo "$(date) $meta"
        if [[ "$meta" != "$colo" ]]; then
          killall sing-box
          sleep 1
        else
          break
        fi
        let i++
      done
    fi
  ;;
  stop)
    echo "Stopping . . . . . ."
    killall sing-box
  ;;
  status)
    echo "Restart . . . . . ."        
    meta=`curl -x socks5://127.0.0.1:1080 -s https://speed.cloudflare.com/meta -m 5 | awk -F\" '{print $22}'`
    echo "$(date) $meta"
  ;;
  *)
    echo "Usage: /etc/init.d/sing-box {start|stop}"
    exit 1
  ;;
esac
exit 0
